---

require:
- rubocop-minitest
- rubocop-rake
- rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
  - lib/asciidoctor/html5s/converter.rb

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 120

Lint/DuplicateMethods:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 35

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Max: 400

Metrics/PerceivedComplexity:
  Enabled: false

Naming/FileName:
  Exclude:
  - lib/asciidoctor-html5s.rb

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodName:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

Rake/Desc:
  Enabled: false

Style/Attr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
